export default {
  mode: 'light',
  background: '#F2F2F2',
  backgroundSecondary: '#fff',
  textColorPrimary: '#414D55',
  textColorSecondary: '#414D55',
  InputBackground: '#FAFBFD',
  Inputplaceholder: '#90A1AC',
  selectBackground: '#edeff569',
  selectProfileBackground: '#dae5ed78',
  checkBoxBackground: '#E4EAF0',
  borderColor: '#A2C0D4',
  borderCalendar: '#DCE2E8',
  backgroundCalendar: '#fff',
  daysWeekCalendar: '#F1F5F8',
  calendarTextColor: '#636D73',
  calendarTextColor2: '#414D55',
  stripesCalendar: '#DCE2E8',
  stripesBackground: '#FAFBFD',
  activeButtonCalendar: '#fff',
  textButtonCalendar: '#2662F0',
  tableTextColor: '#636D73',
  tableBorder: '#f0f0f0',
  tableDescMobileBackground: '#fff',
  backgroundAuth: '#F2F2F2',
  backgroundButtonPomodoro: '#fff',
};
